3 commit
made-ml-in-prod-2021/korowood pull request #2
Opened 2021-04-03 13:33 UTC by korowood

не сразу получилось )

2021-04-03 17:00 UTC, Mikhail-M requested changes

2021-04-03 17:00 UTC, Mikhail-M commented on README.md
> +ШОК КОНТИНЕНТ
Давайте содержание на что-то относящееся к курсу))

2021-04-03 17:08 UTC, korowood commented on README.md
> +ШОК КОНТИНЕНТ
если я изменил файлы, то нужно новый пул реквест создать? а с этим что делать?

2021-04-04 13:30 UTC, Mikhail-M approved these changes

2021-04-04 13:31 UTC, merged