Homework2
made-ml-in-prod-2021/korowood pull request #4
Opened 2021-05-19 20:12 UTC by korowood

1 -  Оберните inference вашей модели в rest сервис (3 балла)

4 - Сделайте валидацию входных данных (3 балла)

5 - Напишите dockerfile, соберите на его основе образ и запустите локально контейнер(docker build, docker run) (4 балла)

6 - Оптимизируйте размер docker image:

Использовал slim версию питона 
в дополнительном файле написал более старые версии библиотек 
# были проблемы с версиями, например одна из версий пандаса не могла прогрузить модель
(думаю 2 балла)

7 - опубликуйте образ в docker.hub (2 балла)

8 - напишите в readme корректные команды docker pull/run, которые должны привести к тому, что локально поднимется на inference ваша модель (1 балл)

проведите самооценку.
(1 балл)

в сумме 16 баллов

2021-05-22 02:38 UTC, polikutinevgeny commented
Дропни, плиз, .venv из репозитория (через .gitignore), это невозможно ревьюить, гитхаб не выдерживает 400+ файлов.

2021-05-22 02:39 UTC, polikutinevgeny requested changes
↑

2021-05-24 07:43 UTC, Mikhail-M requested changes
Коллега прав, уберите .venv, ну и в будущем никогда не коммититьте.

Поревьюить нельзя, поэтому пока что 0

2021-05-24 09:05 UTC, korowood commented
удалил

2021-05-25 11:25 UTC, polikutinevgeny requested changes
Кажется, что лог и .pkl модели стоит тоже добавить в .gitignore

А так, моя оценка:

Валидация на 1 балл из 3, потому что де-факто проверяет, что фичи те же самые, что и были захардкожены.

В остальном у меня явных претензий нет, замечания по коду я свои написал. Итого 14 баллов.

2021-05-25 11:25 UTC, polikutinevgeny commented on online_inference/src/app.py
> +model: Any = None
Возможно вместо глобальной переменной стоит использовать app.state

2021-05-25 11:25 UTC, polikutinevgeny commented on online_inference/src/app.py
> +    return "it is entry point of our predictor"
Зачем?

2021-05-25 11:25 UTC, polikutinevgeny commented on online_inference/src/entities.py
> +            "oldpeak", "slope", "ca", "thal"]
Хардкодить названия фичей, как мне кажется, не хорошо

2021-05-27 08:13 UTC, Mikhail-M commented on online_inference/src/app.py
> +    return "it is entry point of our predictor"
Это у меня так было, для демонстрации))

2021-05-27 08:13 UTC, Mikhail-M commented on online_inference/src/entities.py
> +            "oldpeak", "slope", "ca", "thal"]
не особо хорошо, да

2021-05-27 08:14 UTC, Mikhail-M approved these changes
Баллы: 14
с комментариями и оценкой согласен

2021-05-27 08:52 UTC, merged